[o11y] Add opentelemetry tracing
replit/river pull request #120
Opened 2024-05-12 15:45 UTC by lhchavez

## Why

We want to be able to know what pid2 is doing, and one good way of achieving that is through tracing.

This change is better reviewed with whitespace turned off :sunglasses:.

## What changed

This change adds opentelemetry tracing to river so that we know what's going on.

## Versioning

- [ ] Breaking protocol change
- [ ] Breaking ts/js API change

2024-05-13 00:54 UTC, jackyzha0 commented on package.json
> +    "@opentelemetry/api": "^1.7.0",
should this be a peer dependency? otherwise the global registration won't work properly

2024-05-13 00:54 UTC, jackyzha0 commented on router/server.ts
> +          await tracer.startActiveSpan(
why not 

```ts
const span = tracer.startSpan("do operation");
// do something
span.end();
```

i guess my q is whether `startActiveSpan` gets us anything here because this really affects indentation level/blame which i want to avoid

2024-05-13 13:31 UTC, lhchavez commented on package.json
> +    "@opentelemetry/api": "^1.7.0",
prolly, please help with the fix since i'm not that well-versed in JS tooling.

2024-05-13 13:32 UTC, lhchavez commented on router/server.ts
> +          await tracer.startActiveSpan(
it does :( the machinery here traverses the stack to know what is the currently active context. the implication is that if there were internal spans in any of the service definitions, they _need_ this extra indentation.

let's bite the bullet, we need this.

2024-05-13 16:09 UTC, lhchavez commented on package.json
> +    "@opentelemetry/api": "^1.7.0",
ah nvm found it https://nodejs.org/en/blog/npm/peer-dependencies

2024-05-13 16:35 UTC, jackyzha0 commented on router/server.ts
> +          await tracer.startActiveSpan(
for future readers: https://www.honeycomb.io/blog/startspan-versus-startactivespan-opentelemetry

2024-05-13 18:45 UTC, jackyzha0 requested changes
i wonder if we can get a nicer wrapper API around tracer.startActiveSpan that does all the span stuff for us in a way that auto-ends the spans via a function decorator (seems like all the traces we care about are at the fn level)

this would help us avoid the indentation problem and make this a lot nicer to read

2024-05-13 19:00 UTC, lhchavez commented
> i wonder if we can get a nicer wrapper API around tracer.startActiveSpan that does all the span stuff for us in a way that auto-ends the spans via a function decorator (seems like all the traces we care about are at the fn level)
> 
> this would help us avoid the indentation problem and make this a lot nicer to read

not all of them do, unfortunately. the ones that are done in an async fashion will keep going and need to not be done this way.

re: the indentation problem, we're gonna need to let it go, unfortunately. bite the bullet now.

2024-05-13 19:46 UTC, jackyzha0 commented
seems like they have an 'official' library way to register instrumentations that we should do:

1. example implementation https://github.com/open-telemetry/opentelemetry-js/blob/main/experimental/packages/opentelemetry-instrumentation-http/src/http.ts#L65
2. example usage https://github.com/open-telemetry/opentelemetry-js/tree/main/experimental/packages/opentelemetry-instrumentation-http#usage

2024-05-13 21:42 UTC, lhchavez commented
> seems like they have an 'official' library way to register instrumentations that we should do:
> 
> 1. base pkg https://github.com/open-telemetry/opentelemetry-js/tree/main/experimental/packages/opentelemetry-instrumentation
> 2. example implementation https://github.com/open-telemetry/opentelemetry-js/blob/main/experimental/packages/opentelemetry-instrumentation-http/src/http.ts#L65
> 3. example usage https://github.com/open-telemetry/opentelemetry-js/tree/main/experimental/packages/opentelemetry-instrumentation-http#usage

yeah, that's the recommended way to do it _if_ you don't have access to the code that you're instrumenting (because it's a lot more work involved, and a bit more jank). we do!

2024-05-13 22:03 UTC, lhchavez commented on router/server.ts
> +              kind: SpanKind.SERVER,
ah because just using `kind:` here (the otel way) doesn't show this in the datadog context, which is nice.

2024-05-13 22:04 UTC, lhchavez commented on router/server.ts
> +                if (err instanceof Error) {
why not!

2024-05-13 22:07 UTC, lhchavez commented on transport/transport.ts
> +          span.recordException(String(e));
awww yiss!

2024-05-13 22:07 UTC, lhchavez commented on transport/transport.ts
> +    attempt = 0,
ah rats, forgot to add it to the context.

2024-05-13 22:10 UTC, lhchavez commented on transport/transport.ts
> +    propagation.inject(context.active(), tracing);
/shrug i think it's because the OG implementation is Java. and you know how Java does things.

2024-05-13 23:10 UTC, lhchavez commented on router/server.ts
> +                    disposables.push(() => span.end());
hmm we can go with the same subspan for now. if service writers are doing beefy things in their dispose, they can add a subspan (i guess)

2024-05-14 17:05 UTC, masad-frost commented on tracing/index.ts
> +const tracer = trace.getTracer('river');
```suggestion
const tracer = trace.getTracer('river', RIVER_VERSION);
```

maybe?

2024-05-14 17:43 UTC, lhchavez commented on tracing/index.ts
> +const tracer = trace.getTracer('river');
oooh yes!

2024-05-14 17:50 UTC, lhchavez commented
@masad-frost @jackyzha0 if there are no more comments, mind approving so that we can get better o11y in production?

2024-05-14 21:07 UTC, jackyzha0 approved these changes
have a follow-up pr with some cleanup/code quality in a bit but lgtm for functionality

2024-05-14 21:17 UTC, masad-frost approved these changes
Let's see how this fairs without async context.

2024-05-14 21:17 UTC, masad-frost commented on router/server.ts
> +              },
wonder if we move attributes to a `tracing` type so we don't miss updating one and not others.

2024-05-14 21:17 UTC, masad-frost commented on router/server.ts
> +    }
I wonder if we should use [AsyncLocalStorageContextManager](https://www.npmjs.com/package/@opentelemetry/context-async-hooks) because with async stacks "activeSpan" will be all kinds of messed up. 

Seems like it's marked a stable in node 20 and bun
https://nodejs.org/docs/latest-v20.x/api/async_context.html#class-asynclocalstorage
https://bun.sh/docs/runtime/nodejs-apis#node-async-hooks

That said, I remember AsyncLocalStorage has major performance issues, not sure if tracer incurs those

2024-05-14 21:17 UTC, masad-frost commented on router/server.ts
> +              kind: SpanKind.SERVER,
wonder if it's best to move these to a function to ensure we're consistent across the board. e.g. `startActiveSpan(getProcedureSpanArgs(message, kind))`

2024-05-14 21:18 UTC, masad-frost commented on router/server.ts
> +              },
I guess jacky will can take care of this

2024-05-14 21:18 UTC, masad-frost commented on router/server.ts
> +              kind: SpanKind.SERVER,
jacky can follow up in his pr

2024-05-14 21:24 UTC, jackyzha0 commented on router/server.ts
> +    }
https://www.npmjs.com/package/@opentelemetry/context-zone we might be able to use this?

2024-05-14 21:32 UTC, masad-frost commented on router/server.ts
> +    }
I've used zone.js with Angular, and it had even bigger footguns wrt performance.

IIRC it also makes the package harder to consume due to it patching a lot of internals in the runtime, and last I looked at it, it requires weird UMD setup.

2024-05-14 21:33 UTC, masad-frost commented on router/server.ts
> +    }
we can stick with this for now, if we notice our traces aren't getting nested properly, we can try AsyncLocalStorage and benchmark it.

2024-05-14 21:39 UTC, masad-frost commented on router/server.ts
> +    }
For posterity: chatted offline, we're gonna go with managing context manually!

2024-05-15 01:00 UTC, lhchavez commented on router/server.ts
> +    }
cool, with this convo resolved, i'm going to merge to start getting traces :rocket:

2024-05-15 01:04 UTC, merged