don't log the full transport message in logs
replit/river pull request #149
Opened 2024-05-27 04:40 UTC by jackyzha0

## Why

this caused issues in production with large payload responses (e.g. buffers containing long files)

## What changed

- strip payload and tracing info from logs
- log parsing errors where appropriate

## Versioning

- [ ] Breaking protocol change
- [ ] Breaking ts/js API change

2024-05-27 05:41 UTC, masad-frost requested changes
Maybe we should consider doing this at the passed logger layer. In any case, left some ideas.

2024-05-27 05:41 UTC, masad-frost commented on logging/log.ts
> +          // clone metadata and clean transportMessage
Do we need to copy the whole metadata? I think we can clone only the transport message

2024-05-27 05:41 UTC, masad-frost commented on logging/log.ts
> +const createLogProxy = (log: Logger) =>
We need to wrap 4 known functions, why don't we do that instead of using a proxy. Proxies are great when there's variable fields. Maybe im missing something though.

2024-05-27 05:41 UTC, masad-frost commented on logging/log.ts
> +      get(_target, prop: LoggingLevel) {
There might be other functions in a passed logger, right?

2024-05-27 05:41 UTC, masad-frost commented on logging/log.ts
> +            transportMessage: cleanMessage(metadata.transportMessage ?? {}),
We already check for the transport message above this shouldn't be needed

2024-05-27 05:41 UTC, masad-frost commented on logging/log.ts
> +        return (msg: string, metadata?: MessageMetadata) => {
Maybe we shouldn't strip the data for debug logs?

2024-05-27 05:41 UTC, masad-frost commented on logging/log.ts
> +        return (msg: string, metadata?: MessageMetadata) => {
I've definitely made use of it.

2024-05-27 05:41 UTC, masad-frost commented on transport/transport.ts
> +          ...Value.Errors(OpaqueTransportMessageSchema, parsedMsg),
Nice

2024-05-27 05:57 UTC, jackyzha0 commented on logging/log.ts
> +const createLogProxy = (log: Logger) =>
ya fair point, i had this before i did the wrapper approach so its an artifact of a previous approach

2024-05-27 06:02 UTC, masad-frost approved these changes
Approve in case this is costing us and needs to be patched quick

2024-05-27 06:04 UTC, jackyzha0 commented on logging/log.ts
> +          // clone metadata and clean transportMessage
i think i need this spread to override `transportMessage` without affecting the actual message itself

2024-05-28 16:35 UTC, merged

2024-05-28 16:42 UTC, masad-frost commented on logging/log.ts
> +let _log: Logger | undefined = undefined;
what's this for?

2024-05-28 17:15 UTC, jackyzha0 commented on logging/log.ts
> +let _log: Logger | undefined = undefined;
`_log` is the actual underlying Logger, the `log` is the log proxy that the rest of the library calls into with the full info and it cleans it before calling the underlying `_log`

we just do `Logger | undefined` in the proxy so that we can avoid constructing the objects when a logger is not binded