Don't share servers among tests
replit/river pull request #189
Opened 2024-06-11 19:37 UTC by jackyzha0

## Why

We currently set up a single server that is shared among multiple test
cases. That's undesirable, since we want isolation in each test.

Supercedes #181 and #183

## What changed

- add missing error listener to websocket on the client
- custom onTestFinished

## Versioning

- [ ] Breaking protocol change
- [ ] Breaking ts/js API change

2024-06-11 20:03 UTC, lhchavez approved these changes
hooray! abstractions!

2024-06-11 20:03 UTC, lhchavez commented on __tests__/fixtures/cleanup.ts
> +    onTestFinished: (fn: () => Promise<void>) => {
might be better to not use this name in case there is cargoculting and we accidentally assume certain semantics.

2024-06-11 20:03 UTC, lhchavez commented on transport/impls/ws/client.ts
> +      };
nice!

2024-06-11 20:06 UTC, masad-frost requested changes

2024-06-11 20:06 UTC, masad-frost commented on transport/transport.test.ts
> +      };
wonder if we'll get more vitest surprises with this feature lol

2024-06-11 20:06 UTC, masad-frost commented on transport/transport.test.ts
> +        await postTestChecks();
We run some `expects` in here, are those reported when they fail now that we moved them here?

2024-06-11 20:06 UTC, masad-frost commented on __tests__/fixtures/cleanup.ts
> +    onTestFinished: (fn: () => Promise<void>) => {
i would call this `addPostTestCheck` or something.

2024-06-11 20:06 UTC, masad-frost commented on transport/transport.test.ts
> +        await postTestChecks();
I think we should move our post-test-checks to be at the end of every test instead of adding them here, like what if the test fails, we don't want to run those checks. I don't see a reason for us to be doing it this way.

2024-06-11 20:08 UTC, masad-frost commented
Forgot to leave a specific comment for request:

I don't think we should be running `expect` after the test finishes, we should just inline those in the test, after the test is finished (fails/succeed) we only do cleanups

2024-06-11 20:08 UTC, jackyzha0 commented on transport/transport.test.ts
> +        await postTestChecks();
i did it this way because if the test fails before it hits the end of the test, the cleanup will never run :/

vitest allows assertions in afterEach (beforeEach cleanup is the same as afterEach) and this safely modifies the result of the test

2024-06-11 20:11 UTC, masad-frost commented on transport/transport.test.ts
> +        await postTestChecks();
We can decouple those 2. Clean up is one thing, but it doesn't feel like the right place for assertions, assertions should happen in tests. If we want to test our cleanup logic, we should have tests for the cleanup.

2024-06-12 21:29 UTC, masad-frost approved these changes

2024-06-12 21:29 UTC, merged