[protocolv2] Ignore follow up messages to a stream after server aborts it
replit/river pull request #204
Opened 2024-06-15 20:03 UTC by masad-frost

## Why

When the server aborts a stream (due to invalid request or explicit abort) the client send more messages before it gets the abort. We should make sure this doesn't lead to errors and unnecessary follow up responses.

## What changed

Keep an LRU of aborted streams, if a new message comes in for a stream in our set, we simply ignore the message.

2024-06-17 18:10 UTC, Monkatraz approved these changes
lgtm

2024-06-17 18:10 UTC, Monkatraz commented on router/server.ts
> +
Maybe should go into it's own file? This file is already quite Lorge

2024-06-17 18:10 UTC, Monkatraz commented on router/server.ts
> +  private serverAbortedStreams: LRUSet;
Mainly for discussion: is there a reasonable way to do this that doesn't involve tracking aborted streams like this? I mean it's just a limited size set of strings (and LRU is nice here), so it's relatively harmless, but I wonder if for e.g. multiplayer scenarios (remember classrooms with like 100 people in them?) that you could hit the LRU max size due to the sheer number of aborted streams

(probably just sitting the max size to like 1000 would handle this and not really use that much memory, I don't think the ids are particularly huge)

2024-06-17 18:10 UTC, Monkatraz commented on router/server.ts
> +  }
feels elegant, nice

2024-06-17 22:27 UTC, masad-frost commented on router/server.ts
> +  }
ty :)

2024-06-17 22:28 UTC, jackyzha0 requested changes

2024-06-17 22:28 UTC, jackyzha0 commented on __tests__/abort.test.ts
> +          );
nit

```suggestion
        const handler = vi.fn(() => new Promise(() => {}))

2024-06-17 22:28 UTC, jackyzha0 commented on router/server.ts
> +  private serverAbortedStreams: LRUSet;
i think we could also probably do this based off of the session grace? if we clean up after the session grace elapses we know for certain that there isn't any way we can get a message on that stream

2024-06-17 22:33 UTC, masad-frost commented on router/server.ts
> +  private serverAbortedStreams: LRUSet;
I couldn't think of another way other than tombstones while still reporting unexpected things. I thought abort would be rare enough that it should be ok to have a small number, and yeah, even if we had like 1 million with our typical 18B nanoid that's like barely 1kb

2024-06-17 22:35 UTC, masad-frost commented on __tests__/abort.test.ts
> +          );
I need the types below so that I can get a typed ctx, plus this gives us an easy place to update types as needed.

2024-06-17 22:36 UTC, masad-frost commented on router/server.ts
> +  private serverAbortedStreams: LRUSet;
@jackyzha0 i don't think it's worth the complexity of setting up a separate set for every session or another mapping.

2024-06-17 22:36 UTC, masad-frost commented on router/server.ts
> +  private serverAbortedStreams: LRUSet;
starting a timeout is pretty expensive especially if we do that for every abort

2024-06-17 22:37 UTC, masad-frost commented on router/server.ts
> +  private serverAbortedStreams: LRUSet;
using session status i guess is fine, but still is it worth the extra map to protect against keeping around extra strings? Maybe some consideration around streamId conflicts?

2024-06-17 22:38 UTC, masad-frost commented on router/server.ts
> +  private serverAbortedStreams: LRUSet;
i meant 1mb for 1 million ids

2024-06-17 22:39 UTC, jackyzha0 commented on router/server.ts
> +  private serverAbortedStreams: LRUSet;
hm yeah i was thinking we could just keep streams around until they are disconnected for good (i.e. we only cleanup streams on session disconnect and aborts still keep streams around), wdyt

2024-06-17 22:39 UTC, Monkatraz commented on router/server.ts
> +  private serverAbortedStreams: LRUSet;
yeah all-in-all this way of doing it is pretty elegant, no timers, doesn't grow infinitely, etc etc.

it would take a fairly wacky situation for this to break

2024-06-17 22:42 UTC, jackyzha0 commented on router/server.ts
> +  private serverAbortedStreams: LRUSet;
i'd prefer a never-breaks solution over a probabilistic one where possible and its not too expensive to, i think keeping streams around until session grace elapses isnt that bad and we aren't adding new timers

2024-06-17 23:05 UTC, masad-frost commented on router/server.ts
> +    abortedStreamsMaxTombstones: number;
make this optional

2024-06-18 18:55 UTC, jackyzha0 approved these changes

2024-06-18 18:55 UTC, jackyzha0 commented on .replit
> +
oop

2024-06-20 17:46 UTC, merged