leaky bucket connection retry rate limit
replit/river pull request #67
Opened 2024-03-29 01:48 UTC by jackyzha0

## why
- our retry logic didn't handle cases where a connection appears successful (i.e. we get an 'open' message) and then is immediately closed
  - this can end up in connection spam
- we should globally add some form of rate-limiting at a transport-level per node it is attempting to connect to

## what changed
- add leaky bucket rate limiting so we dont spam retry even on connections that open and then immediately close
- add arg `retryBudgetRestoreRateMs` that controls how often we refill the bucket
- `connect` promise lifetime is now accurate across retries
- add test `repeated connections that close instantly causes retry limit to still be reached`

2024-03-29 06:26 UTC, masad-frost commented on __tests__/negative.test.ts
> +  test('repeated connections that close instantly causes retry limit to still be reached', async () => {
:man_cook:

2024-03-29 17:22 UTC, masad-frost reviewed
Nice quick turn around.

Left some comments, lemme know what you think.

2024-03-29 17:22 UTC, masad-frost commented on __tests__/negative.test.ts
> +    });
when do you use this vs just doing it at the end?

2024-03-29 17:22 UTC, masad-frost commented on transport/transport.ts
> +class LeakyBucketLimit {
might be worth a test on this class?

2024-03-29 17:22 UTC, masad-frost commented on transport/transport.ts
> +class LeakyBucketLimit {
wonder if building the backoff into this makes sense, like make it return a backoff exponent instead of just a limit? We can get rid of the attempt counter altogether that way and maintain backoffs across connections, instead of just per connection cycle.

2024-03-29 17:22 UTC, masad-frost commented on transport/transport.ts
> -    this.inflightConnectionPromises.delete(session.to);
why is this not needed anymore?

2024-03-29 17:22 UTC, masad-frost commented on transport/transport.ts
> +      if (budgetConsumed >= this.options.retryAttemptsMax) {
I think this option might be a misnomer now.

2024-03-29 17:22 UTC, masad-frost commented on transport/transport.ts
> +  retryBudgetRestoreRateMs: 500,
Feels like way too low, I think on the order of seconds makes more sense to me.

2024-03-29 17:31 UTC, jackyzha0 commented on transport/transport.ts
> -    this.inflightConnectionPromises.delete(session.to);
we moved this to be done after a connection fails, `onDisconnect` is only called for connections that have completed a handshake so we need to also handle the case when the server just received a connection and it closed immediately without handshake completing

2024-03-29 17:31 UTC, jackyzha0 commented on transport/transport.ts
> +class LeakyBucketLimit {
oh true 🤔 lemme try my hand at a refactor

2024-03-29 17:33 UTC, jackyzha0 commented on __tests__/negative.test.ts
> +    };
crazyyy

2024-03-29 17:33 UTC, jackyzha0 commented on __tests__/negative.test.ts
> +    });
this handles cases where a test fails and throws before we reach the end of the test (its kinda like a .finally)

2024-03-29 17:46 UTC, masad-frost commented on transport/transport.ts
> +class LeakyBucketLimit {
slack'd you a suggestion

2024-04-01 23:20 UTC, masad-frost commented on transport/transport.ts
> +  maxReconnectionBurstAttempts: number;
good name

2024-04-01 23:37 UTC, masad-frost requested changes
I think we're losing our backoff with this unfortunately. We can make the drainage time astronomical which would put us at risk of not being able to reconnect when we should be able to. My recommendation is  to defer it until we connect, the example i sent you does that. Otherwise we're running the risk of little to no backoff.

I just tried it in the console, I can barely get the backoff to grow unless i'm spamming consume budget, feel free to try it.

```js
class LeakyBucketRateLimit {
    constructor(options) {
        this.options = options;
        this.budgetConsumed = new Map();
        // start leaking
        this.intervalHandle = setInterval(() => {
            for (const [user, budgetConsumed] of this.budgetConsumed.entries()) {
                const newBudget = budgetConsumed - 1;
                console.log('lower budget for', user, budgetConsumed)
                if (newBudget === 0) {
                    this.budgetConsumed.delete(user);
                }
                else {
                    this.budgetConsumed.set(user, newBudget);
                }
            }
        }, this.options.leakIntervalMs);
    }
    get drainageTimeMs() {
        return this.options.leakIntervalMs * this.options.maxBurst;
    }
    getBackoffMs(user) {
        if (!this.budgetConsumed.has(user))
            return 0;
        const exponent = Math.max(0, this.getBudgetConsumed(user) - 1);
        const jitter = Math.floor(Math.random() * this.options.jitterMs);
        const backoffMs = this.options.baseIntervalMs * 2 ** exponent + jitter;
        return backoffMs;
    }
    consumeBudget(user) {
        this.budgetConsumed.set(user, this.getBudgetConsumed(user) + 1);
    }
    getBudgetConsumed(user) {
        return this.budgetConsumed.get(user) ?? 0;
    }
    close() {
        clearInterval(this.intervalHandle);
    }
}
l = new LeakyBucketRateLimit({maxBurst: 1000, leakIntervalMs: 2000, baseIntervalMs: 250, jitterMs: 500 })
u = 'user'
```

and then try this in the console.

```js
l.consumeBudget(u)
console.log('backoff', l.getBackoffMs(u))
console.log('consumed', l.getBudgetConsumed(u))
```
it doesn't feel right to me. WDYT?

2024-04-01 23:37 UTC, masad-frost commented on transport/transport.ts
>    retryJitterMs: number;
this should be `maxRetryJitterMs` right?

2024-04-01 23:37 UTC, masad-frost commented on transport/transport.ts
>    retryJitterMs: number;
maybe we should put these under a single object, `retryOptions` or something.

2024-04-01 23:37 UTC, masad-frost commented on transport/rateLimit.ts
> +    return backoffMs;
We should probably have a maximum backoff now that we don't have max attempts and things are time based.

2024-04-01 23:37 UTC, masad-frost commented on transport/rateLimit.ts
> +    }, this.options.leakIntervalMs);
I really dislike that budgets start getting refreshed as soon as you consume. If your `leakIntervalMs` isn't much much higher than the duration it takes to establish a connection, then you're probably not really implementing exponential backoff, you just have normal backoff. You can also end up in a situation where you have 2 tries 1ms apart that get 0 backoff because of the timing (e.g. right before the interval hits).

2024-04-01 23:37 UTC, masad-frost commented on transport/rateLimit.ts
> +  }
should these be the one function?

2024-04-01 23:42 UTC, jackyzha0 commented on transport/rateLimit.ts
> +    }, this.options.leakIntervalMs);
do you think we should start a separate interval for each budget?

2024-04-01 23:53 UTC, masad-frost commented on transport/rateLimit.ts
> +    }, this.options.leakIntervalMs);
Yeah let's do that, probably enough.

2024-04-01 23:53 UTC, masad-frost approved these changes

2024-04-02 05:03 UTC, jackyzha0 commented on transport/rateLimit.ts
> +  maxBackoffMs: number;
should probably mention that we default to an exponential backoff and cap the result by this number

2024-04-02 05:03 UTC, jackyzha0 commented on transport/rateLimit.ts
> +  maxAttempts: number;
when i read this, it feels weird that we need to define this along with `maxBackoffMs`, imo should be one or the other? 

maybe `attemptCapacity` is better at conveying the semantics of how we actually use it to calculate

2024-04-02 18:26 UTC, masad-frost commented on transport/transport.ts
> +          this.retryBudget.startRestoringBudget(to);
no u

2024-04-02 18:26 UTC, masad-frost commented on transport/rateLimit.ts
> +    this.stopLeak(user);
Intuitively, this feels right. idk

2024-04-02 18:27 UTC, masad-frost commented on transport/rateLimit.ts
> +  maxAttempts: number;
Yeah something feels off now that we're not leaking while we're attempting. Good name

2024-04-02 18:45 UTC, jackyzha0 commented on transport/rateLimit.ts
> +    this.stopLeak(user);
ya that makes sense too, just didnt get that immediately haha

2024-04-02 21:40 UTC, jackyzha0 commented
![image](https://github.com/replit/river/assets/23178940/b69da0b2-4b34-4e1b-be6a-86e84c88dd9e)

me reviewing my own pr

2024-04-02 21:54 UTC, merged